# Generated by Django 5.2.16 on 2026-07-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_project_is_published_projectupdatelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequest',
            name='care_request_type',
            field=models.CharField(choices=[('none', 'No Additional Care Needed'), ('pastoral_call', 'Pastoral Call'), ('elder_visit', 'Elder Visit'), ('counseling', 'Counseling Support'), ('prayer_partner', 'Prayer Partner')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='follow_up_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='follow_up_status',
            field=models.CharField(choices=[('received', 'Received'), ('assigned', 'Assigned to Prayer Team'), ('contacted', 'Contacted'), ('ongoing', 'Ongoing Prayer Support'), ('completed', 'Follow-up Completed')], default='received', max_length=30),
        ),
        migrations.AddField(
            model_name='testimony',
            name='next_step',
            field=models.CharField(choices=[('none', 'No Follow-up Needed'), ('mentor', 'Connect to Mentor'), ('growth_class', 'Invite to Growth Class'), ('prayer_team', 'Connect to Prayer Team'), ('service_team', 'Connect to Service Team')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='testimony',
            name='testimony_type',
            field=models.CharField(choices=[('prayer_answered', 'Prayer Answered'), ('spiritual_growth', 'Spiritual Growth'), ('community_support', 'Community Support'), ('healing_restoration', 'Healing and Restoration'), ('outreach_impact', 'Outreach Impact')], default='spiritual_growth', max_length=50),
        ),
    ]
