# Generated by Django 5.2.16 on 2026-07-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_prayerrequest_care_request_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='action_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='audience',
            field=models.CharField(choices=[('all_church', 'All Church'), ('youth', 'Youth'), ('leaders', 'Leaders'), ('new_members', 'New Members'), ('ministry_team', 'Ministry Team')], default='all_church', max_length=30),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cta_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cta_text',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='mission_tag',
            field=models.CharField(choices=[('prayer', 'Prayer'), ('strengthening', 'Strengthening'), ('growth', 'Growth'), ('service', 'Service'), ('worship', 'Worship'), ('administration', 'Administration')], default='administration', max_length=30),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20),
        ),
    ]
