# Generated by Django 5.2.16 on 2026-07-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoBackToSchoolPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(default='go-back-to-school', max_length=80, unique=True)),
                ('hero_title', models.CharField(default='Go Back to School Project', max_length=255)),
                ('hero_subtitle', models.TextField(default='Volunteers like you are the reason children go back to class')),
                ('overall_fundraising_title', models.CharField(default='Current Fundraising Campaign', max_length=255)),
                ('overall_fundraising_copy', models.TextField(default="We are raising funds for students this term. Every contribution goes 100% directly to a student's education.")),
                ('overall_stats', models.JSONField(default=list)),
                ('student_cases', models.JSONField(default=list)),
                ('ways_to_give', models.JSONField(default=list)),
                ('impact_levels', models.JSONField(default=list)),
                ('contact_points', models.JSONField(default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['page_key'],
            },
        ),
    ]
