# Generated by Django 5.2.16 on 2026-08-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_gobacktoschoolpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblestudy',
            name='group_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]