# Generated by Django 5.2.16 on 2026-08-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_biblestudy_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleStudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('topic', models.CharField(blank=True, default='', max_length=255)),
                ('meeting_day', models.CharField(blank=True, default='', max_length=40)),
                ('meeting_time', models.CharField(blank=True, default='', max_length=40)),
                ('format', models.CharField(blank=True, choices=[('in_person', 'In Person'), ('online', 'Online'), ('hybrid', 'Hybrid')], default='', max_length=30)),
                ('leader_name', models.CharField(blank=True, default='', max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('max_members', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
